name: Node CI

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v3
    - run: npm install
    - run: npm test
